---

- name: Disable Telemetry via group policy
  when: disable_telemetry_policy
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: AllowTelemetry
    data: 0
    type: dword

- name: Block Windows telemetry hosts at DNS level
  when: disable_telemetry_dnsblock
  ansible.windows.win_copy:
    content: |
      {% for hostname in disable_telemetry_dnsblock_fqdns %}
      0.0.0.0 {{ hostname }}
      {% endfor %}
    dest: "{{ ansible_env.SystemRoot }}\\System32\\drivers\\etc\\hosts"

- name: Add telemetry IPs to Windows Firewall
  when: disable_telemetry_dnsblock
  community.windows.win_firewall_rule:
    name: Block Telemetry IPs (ansible-role-debloat-windows)
    state: present
    enabled: true
    direction: out
    action: block
    remoteip: "{{ disable_telemetry_dnsblock_ip_addresses | join(',') }}"
